-- 001_create_users.sql
--
-- Accounts for the Primary_User (Owner_Role) and read-only Viewers (Viewer_Role).
--
-- Requirements: 1.2 (email uniqueness after normalisation), 4.5 (deletion clock),
--               7.1 (viewer linked to the owner's data), 7.4 (revocation), 2.3 (lockout).
--
-- Notes:
--   * `id` is a ULID generated by the application (26 Crockford base32 characters).
--   * `email_normalized` is trimmed and lowercased by Auth_Service before the uniqueness
--     check, and stored with a binary collation so database equality is exactly
--     normalised-string equality rather than a locale-dependent comparison.
--   * `data_owner_id` is self-referential: an owner points at itself, a viewer points at
--     the owner whose data it may read. ON DELETE CASCADE means purging an owner also
--     removes the viewer accounts linked to it (Requirement 4.5).
--   * No plaintext health data lives in this table, so nothing here is encrypted.
--   * All DATETIME values are written by the application in UTC.

CREATE TABLE users (
    id                    CHAR(26)                        NOT NULL,
    email_normalized      VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    email_display         VARCHAR(255)                    NOT NULL,
    password_hash         VARCHAR(255)                    NULL,
    role                  ENUM('owner','viewer')          NOT NULL,
    data_owner_id         CHAR(26)                        NOT NULL,
    status                ENUM('invited','active','revoked') NOT NULL DEFAULT 'invited',
    failed_login_count    TINYINT UNSIGNED                NOT NULL DEFAULT 0,
    locked_until          DATETIME                        NULL,
    deletion_requested_at DATETIME                        NULL,
    created_at            DATETIME                        NOT NULL,
    updated_at            DATETIME                        NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email_normalized (email_normalized),
    KEY idx_users_data_owner (data_owner_id),
    KEY idx_users_deletion_requested_at (deletion_requested_at),
    CONSTRAINT fk_users_data_owner
        FOREIGN KEY (data_owner_id) REFERENCES users (id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  ROW_FORMAT = DYNAMIC;
